<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // type 0 = like , type 1 = comment
        $notifications = [
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 1,
                'comment_id' => null,
                'photo_image_id' => 10,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 2,
                'comment_id' => null,
                'photo_image_id' => 1,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 3,
                'comment_id' => null,
                'photo_image_id' => 2,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 3,
                'comment_id' => null,
                'photo_image_id' => 3,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 3,
                'comment_id' => null,
                'photo_image_id' => 5,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 6,
                'comment_id' => null,
                'photo_image_id' => 8,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 7,
                'comment_id' => null,
                'photo_image_id' => 9,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 9,
                'comment_id' => null,
                'photo_image_id' => 12,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 33,
                'comment_id' => null,
                'photo_image_id' => 112,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 1,
                'recipient_id' => 3,
                'like_id' => 33,
                'comment_id' => null,
                'photo_image_id' => 23,
                'type' => 0,
                'content' => 'Your photo has been liked!',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 1,
                'photo_image_id' => 15,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 2,
                'photo_image_id' => 12,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 3,
                'photo_image_id' => 31,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 4,
                'photo_image_id' => 12,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 5,
                'photo_image_id' => 23,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 12,
                'photo_image_id' => 23,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 23,
                'photo_image_id' => 15,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 34,
                'photo_image_id' => 15,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 44,
                'photo_image_id' => 15,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
            [
                'user_id' => 2,
                'recipient_id' => 3,
                'like_id' => null,
                'comment_id' => 55,
                'photo_image_id' => 15,
                'type' => 1,
                'content' => 'Your photo received a new comment.',
                'is_read' => false,
                'notification_date' => now(),
            ],
        ];

        foreach ($notifications as $notification) {
            DB::table('notifications')->insert($notification);
        }
    }
}
